### ISSUE TITLE
Uptime=0 macht division-by-zero Fehler

### ISSUE THREAD

**Issue by adschm** [asdil12/ff-map#203]
{2019-07-01 19:40:01} - Warning: Exception occurred when saving xxxx: division by zero
__Traceback (most recent call last):
__  File "/usr/local/lib/python3.5/dist-packages/ffmap/routertools.py", line 160, in import_nodewatcher_xml
__    calculate_network_io(mysql, router_id, uptime, router_update)
__  File "/usr/local/lib/python3.5/dist-packages/ffmap/routertools.py", line 669, in calculate_network_io
__    netif_update["traffic"]["rx"] = int(netif_update["traffic"]["rx_bytes"] / router_update["sys_uptime"])
__ZeroDivisionError: division by zero
__

**Comment by adschm** [comment]
Fixed in 01b5223b5a8110845d843dd836e170dbb411b1fb.
