### ISSUE TITLE
Installationsbugs

### ISSUE THREAD

**Issue by ChristianDresel** [asdil12/ff-map#225]
Folgendes fehlt bei der Installation (vermutlich einfach in install.sh):

mkdir /data/fff/fffmonlog/
chown -R www-data:www-data /data/fff/fffmonlog/

sonst läuft die API nicht.

Zudem fehlt in der Beschreibung wo man

git clone https://github.com/asdil12/fff-monitoring
git clone https://github.com/TileStache/TileStache

hinlegen soll, nämlich nach /data/fff/

**Comment by ChristianDresel** [comment]
Bei Python 3.9 bin ich über ein weiteres Problem gestolpert. 

/data/fff/TileStache/TileStache/py3_compat.py

from cgi import parse_qs

gibt es so nicht mehr, das parse_qs kommt nun aus urllib.parse

Ich hab das jetzt einfach händisch drüber gefummelt da ich mich da zu wenig auskenne, aber damit läuft nun auch das TileStache

**Comment by ChristianDresel** [comment]
Aktuell läuft dieser TileStache auch noch nicht korrekt, ich finde aber gerade den Fehler noch nicht. Es scheinen Files in 

/var/lib/ffmap/csv/*

zu fehlen, dieser Ordner ist leer und deshalb malt er anscheinend auch nich auf der Karte herum:

Feb 12 09:26:45 moni uwsgi_python3[14659]: Traceback (most recent call last):
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/__init__.py", line 393, in __call__
Feb 12 09:26:45 moni uwsgi_python3[14659]:     status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/__init__.py", line 266, in requestHandler2
Feb 12 09:26:45 moni uwsgi_python3[14659]:     status_code, headers, content = layer.getTileResponse(coord, extension)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/Core.py", line 426, in getTileResponse
Feb 12 09:26:45 moni uwsgi_python3[14659]:     tile = self.render(coord, format)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/Core.py", line 508, in render
Feb 12 09:26:45 moni uwsgi_python3[14659]:     tile = provider.renderArea(width, height, srs, xmin, ymin, xmax, ymax, coord.zoom)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/usr/local/lib/python3.9/dist-packages/dynmapnik.py", line 21, in renderArea
Feb 12 09:26:45 moni uwsgi_python3[14659]:     return TileStache.Providers.Mapnik.renderArea(self, *args, **kwargs)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/Mapnik.py", line 137, in renderArea
Feb 12 09:26:45 moni uwsgi_python3[14659]:     self.mapnik = get_mapnikMap(self.mapfile)
Feb 12 09:26:45 moni uwsgi_python3[14659]:   File "/data/fff/TileStache/TileStache/Mapnik.py", line 435, in get_mapnikMap
Feb 12 09:26:45 moni uwsgi_python3[14659]:     mapnik.load_map(mmap, str(mapfile))
Feb 12 09:26:45 moni uwsgi_python3[14659]: RuntimeError: could not create file mapping for /var/lib/ffmap/csv/links_local.csv  encountered during parsing of layer 'links' in Layer at line 86 of '/usr/share/ffmap/routers_local.xml'
Feb 12 09:26:45 moni uwsgi_python3[14659]: [pid: 14659|app: 0|req: 135/404] xxx () {50 vars in 859 bytes} [Sat Feb 12 09:26:45 2022] GET /tiles/routers_local/18/139091/89504.png => generated 0 bytes in 1 msecs (HTTP/1>

in /var/lib/ffmap/csv/ liegt nichts drinnen deshalb sieht er die xml als ungültig an weil er die csv nicht findet. Mir ist aktuell noch unklar wo diese Daten herkommen sollen
